### ISSUE TITLE
Exception when iframe content not fully loaded

### ISSUE THREAD

**Issue by abinggeli** [nicholashamilton/craft-preview-mate#1]
I get the following runtime error on certain pages:

`PreviewMate.js?v=1707043428:110 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at PreviewMate.js?v=1707043428:110:78
    at Array.forEach (<anonymous>)
    at Object.attatchPreviewBlockEventListeners (PreviewMate.js?v=1707043428:96:53)
    at Object.initDevicePreviewIframe (PreviewMate.js?v=1707043428:85:31)
    at Object.initPreviewModule (PreviewMate.js?v=1707043428:54:31)`

After a bit of debugging, I noticed that the content of the iframe is null when pages are complex and take longer to load. As a local fix I check for the iframe to be fully loaded:

`iframe.addEventListener("load", function() {
   const previewBlocks = iframe.contentWindow.document.body.querySelectorAll(previewBlocksQuery);
   ...`

**Comment by nicholashamilton** [comment]
Hey @abinggeli, I haven't been able to reproduce the error yet but i've looked through the code and see where there could be an issue.

Can you test the PreviewMate.js code in pull request #2 and see if that fixes the error you're encountering?

Thanks! - Nick

**Comment by abinggeli** [comment]
Hi Nick,

Yeah, the pull request solves my problem. Many thanks for the quick fix. The plugin is really super helpful.

Best regards,
Andy

**Comment by nicholashamilton** [comment]
Hey @abinggeli, 

It's great to hear that PR solved the issue. Thank you bringing awareness to that! 

Glad you are enjoying the plugin 🎉

I'll be releasing an update with the changes later today.

**Comment by nicholashamilton** [comment]
Hey @abinggeli, 

It's great to hear that PR solved the issue. Thank you bringing awareness to that! 

Glad you are enjoying the plugin 🎉

I'll be releasing an update with the changes later today.
