### ISSUE TITLE
Problems in combination with Blitz caching plugin

### ISSUE THREAD

**Issue by abinggeli** [nicholashamilton/craft-preview-mate#3]
Hi Nick, I have encountered another problem in connection with the Blitz caching plugin. When I activate the plugin, the PreviewMate plugin no longer works. Blitz does not cache pages in preview mode, yet it behaves differently whether I have activated or deactivated the plugin. I have also tried the various caching exclusions but nothing has helped. It looks like the asynch getSettings method fails. Do you have an idea how this can be fixed?

<img width="1049" alt="image" src="https://github.com/nicholashamilton/craft-preview-mate/assets/25820742/c7967fea-580a-4b0a-ac9d-c51690c46415">

**Comment by nicholashamilton** [comment]
Hey @abinggeli , sorry for the late response. I'm excited to announce we have released v3 today which adds CraftCMS 5 support.

In v3, the `config/preview-mate.php` has been removed entirely.

I've tested v3 with Blitz and it appears to be working.

Check out the `craft-5` branch readme for updated instructions.

**Comment by abinggeli** [comment]
Hi Nicholas, 

Thank you very much for the update. Unfortunately, the customer's website is still on Craft 4. An update to Craft 5 is not planned at the moment. It seems that the plugin in version 3.x and 4.x only works with Craft 5? I tried the dev-craft-4 branch, but I couldn't get it to work. Is there a solution for Craft 4?

Best regards,
Andy

**Comment by nicholashamilton** [comment]
Hey @abinggeli,

Are there any syntax issues within your `config/preview-mate.php` by chance (I doubt it if it works with Blitz disabled)?

I'm not sure why `Blitz` is causing the HTTP request to error. I have not been able to replicate this on `craft-4` with the `Blitz` plugin enabled on my end. Is there any additional info on the HTTP request that you can provide for debugging?
